# Dependencies
markdown:            redcarpet
highlighter:         pygments
excerpt_separator:   "\n\n"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hello world!
tagline:             '</p>'
description:         '互联网新兵，用0和1编织你我梦想！'
url:                 http://jim2013.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jim Lao
  url:               http://jim2013.github.io/
  email:             developer.lao@gmail.com

# Custom vars
version:             1.0.0
